### ISSUE TITLE
HTMSensor returns null instead of empty Optional

### ISSUE THREAD

**Issue by clumsy** [numenta/htm.java#249]
A short recipe for crashes due to cryptic NPE:

```java
Exception in thread "main" java.lang.NullPointerException
	at org.numenta.nupic.network.sensor.HTMSensor.makeIndexEncoderMap(HTMSensor.java:179)
	at org.numenta.nupic.network.sensor.HTMSensor.initEncoder(HTMSensor.java:539)
	at org.numenta.nupic.network.Network.setSensor(Network.java:455)
	at org.numenta.nupic.network.Region.setNetwork(Region.java:121)
	at org.numenta.nupic.network.Network.add(Network.java:395)
```

Other encoders have the same problem.

**Comment by cogmission** [comment]
@clumsy Hi, thanks for getting involved.

Can you provide the steps to reproduce this?

Thanks.

**Comment by clumsy** [comment]
Sure, actually I'm in the middle of contributing a fix and a bunch of unit tests.
The short answer is to try declare category in sensor file with no category encoder registered.
Not that this is a normal scenario, but the output could have been more descriptive.

**Comment by cogmission** [comment]
Sure, I am working on documentation - a rather big task; so full API coverage is a work in progress. Your help is certainly appropriated - let me know what I can do to help.

**Comment by cogmission** [comment]
@clumsy  @rhyolight  Also please fill out Numenta's Contributor's License Agreement Here: http://numenta.org/licenses/cl/ - let me know when you've submitted it... Thanks...

**Comment by clumsy** [comment]
OK, singed the CLA and here's the patch: https://github.com/numenta/htm.java/pull/251
