### ISSUE TITLE
ArrayIndexOutOfBoundsException in computeActivity

### ISSUE THREAD

**Issue by mrcslws** [numenta/htm.java#482]
Running NAB, I got

~~~
ava.lang.ArrayIndexOutOfBoundsException: 1017
	at org.numenta.nupic.Connections.computeActivity(Connections.java:1199)
	at org.numenta.nupic.algorithms.TemporalMemory.compute(TemporalMemory.java:176)
	at org.numenta.nupic.network.Layer.temporalInput(Layer.java:1942)
	at org.numenta.nupic.network.Layer$FunctionFactory$2.call(Layer.java:2287)
	at org.numenta.nupic.network.Layer$FunctionFactory$2.call(Layer.java:2276)
	at rx.internal.operators.OperatorMap$1.onNext(OperatorMap.java:55)
	at rx.internal.operators.OperatorMap$1.onNext(OperatorMap.java:55)
	at rx.internal.operators.OperatorMap$1.onNext(OperatorMap.java:55)
	at rx.internal.operators.OperatorFilter$1.onNext(OperatorFilter.java:54)
	at rx.internal.operators.OperatorMap$1.onNext(OperatorMap.java:55)
	at rx.internal.operators.OperatorCast$1.onNext(OperatorCast.java:50)
	at rx.internal.operators.OperatorFilter$1.onNext(OperatorFilter.java:54)
	at rx.subjects.SubjectSubscriptionManager$SubjectObserver.onNext(SubjectSubscriptionManager.java:224)
	at rx.subjects.PublishSubject.onNext(PublishSubject.java:114)
	at org.numenta.nupic.network.Layer.compute(Layer.java:939)
	at org.numenta.nupic.network.Layer$5.lambda$run$38(Layer.java:1986)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.numenta.nupic.network.Layer$5.run(Layer.java:1983)
Caused by: rx.exceptions.OnErrorThrowable$OnNextValue: OnError while emitting onNext value: org.numenta.nupic.network.ManualInput.class
	at rx.exceptions.OnErrorThrowable.addValueAsLastCause(OnErrorThrowable.java:101)
	at rx.internal.operators.OperatorMap$1.onNext(OperatorMap.java:58)
	... 21 more
~~~

I "fixed" it by choosing a different random seed.

My guess is this is related to the `flatIdx` not getting properly recycled in destroyed segments. I've seen similar issues in the Python/C++.

**Comment by cogmission** [comment]
@mrcslws You are AWESOME!

Thanks Marcus. Do you happen to remember an example of a failing seed?

**Comment by mrcslws** [comment]
The one that's passed in by `htmjava_detector.py` hits this exception.

**Comment by cogmission** [comment]
Is there any reason to _ever_ vary the seed? I don't understand this practice? Seems silly...?

Also, do you think this will go away when I sync with the latest TM code? Since "destroyed segments" aren't reused in the latest TM code. (I could be wrong, but I think that's the difference?)

**Comment by mrcslws** [comment]
Well, there's a random number generator, so we might as well give ourselves control of the seed.

It might go away with the next sync, but keep in mind there's still a `_freeFlatIdxs` list. A little bit of recycling still happens.
